/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.2).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package j2ee.demo.controller;

import j2ee.demo.model.Moment;
import io.swagger.annotations.*;
import j2ee.demo.utils.Response;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2018-12-10T17:01:42.314Z[GMT]")

@Api(value = "discoveries", description = "the discoveries API")
@RestController
public class DiscoveriesController {

    @ApiOperation(value = "获得用户发现页", nickname = "discoveriesUserIdGet", notes = "", response = Moment.class, responseContainer = "List", tags = {"discovery",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功找到发现页", response = Moment.class, responseContainer = "List"),
            @ApiResponse(code = 404, message = "用户不存在")})
    @RequestMapping(value = "/discoveries/{UserId}",
            produces = {"application/json"},
            method = RequestMethod.GET)
    Response discoveriesUserIdGet(@ApiParam(value = "", required = true) @PathVariable("UserId") Integer userId) {
        return null;
    }

}
