/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.2).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package j2ee.demo.controller;

import com.google.gson.JsonObject;
import io.swagger.annotations.*;
import j2ee.demo.elasticsearch.MomentDocumentService;
import j2ee.demo.model.Moment;
import j2ee.demo.utils.ErrorResult;
import j2ee.demo.utils.GetJsonContentUtils;
import j2ee.demo.utils.Response;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2018-12-10T17:01:42.314Z[GMT]")

@CrossOrigin("*")
@Api(value = "_search", description = "the _search API")
@RestController
public class SearchController {

    @Autowired
    private MomentDocumentService momentDocumentService;

    @ApiOperation(value = "搜索内容", nickname = "searchGet", notes = "", tags = {"search",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功找到发现页"),
            @ApiResponse(code = 404, message = "未找到相关结果")})
    @RequestMapping(value = "/search/{keyword}",
            method = RequestMethod.GET)
    public ResponseEntity<Object>  searchGet(@ApiParam(value = "", required = true) @PathVariable("keyword") String keyword) {
        List<Moment> findInContent = momentDocumentService.findByContent(keyword);
        List<Moment> findInTag = momentDocumentService.findByTags(keyword);
        if (findInContent == null && findInTag == null) {
            return new ResponseEntity<>(new ErrorResult("未找到相关结果"), HttpStatus.NOT_FOUND);
        } else {
            JsonObject receive = new JsonObject();
            receive.add("contnet", GetJsonContentUtils.transListToJsonArray(findInContent));
            receive.add("tag", GetJsonContentUtils.transListToJsonArray(findInTag));
            return new ResponseEntity<>(receive.toString(), HttpStatus.OK);
        }
    }
}
