/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.2).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package j2ee.demo.controller;

import io.swagger.annotations.*;
import j2ee.demo.utils.Response;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2018-12-10T17:01:42.314Z[GMT]")

@Api(value = "_search", description = "the _search API")
@RestController
public class SearchController {

    @ApiOperation(value = "搜索内容", nickname = "searchGet", notes = "", tags = {"search",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "成功找到发现页"),
            @ApiResponse(code = 404, message = "未找到相关结果")})
    @RequestMapping(value = "/_search",
            method = RequestMethod.GET)
    public ResponseEntity<Object>  searchGet() {
        return null;
    }

}
