server:
  port: 8080
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/igallery
  jpa:
    hibernate:
      ddl-auto: update #自动更新
    show-sql: true  #日志中显示sql语句

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

mybatis:
  typeAliasesPackage: j2ee.demo.model
  mapperLocations: classpath:mapper/*.xml

#elasticsearch:
#  ip: 127.0.0.1
#  port: 9300
#  pool: 5
#  cluster:
#    name: elasticsearch

